set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'   " plugin manager
Plugin 'tpope/vim-fugitive'	" for git
Plugin 'benmills/vimux'		" tmux + vim
Plugin 'scrooloose/nerdtree'	" Nerdtree for file drawer
Plugin 'airblade/vim-gitgutter' " git gutter
Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'} 
call vundle#end()            " required
filetype plugin indent on    " required

set laststatus=2
set t_Co=256
